"""codex-open-client — Python client for OpenAI Codex."""

from codex_open_client._api import build_headers, get_account_id
from codex_open_client._auth import (
    PendingLogin,
    finish_login,
    get_token,
    login,
    refresh,
    start_login,
)
from codex_open_client._client import CodexClient
from codex_open_client._errors import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthError,
    CodexError,
    ContextWindowError,
    InvalidRequestError,
    QuotaExceededError,
    RateLimitError,
    ServerError,
    StreamError,
)
from codex_open_client._types import (
    ContentPart,
    FormatConfig,
    FunctionCallOutput,
    FunctionTool,
    InputImage,
    InputItem,
    InputMessage,
    InputText,
    Model,
    OutputContent,
    OutputItem,
    OutputText,
    ParsedResponse,
    Reasoning,
    ReasoningSummary,
    Response,
    ResponseCompletedEvent,
    ResponseCreatedEvent,
    ResponseError,
    ResponseFailedEvent,
    ResponseFormatJsonObject,
    ResponseFormatJsonSchema,
    ResponseFormatText,
    ResponseFunctionCallArgumentsDeltaEvent,
    ResponseFunctionCallArgumentsDoneEvent,
    ResponseFunctionToolCall,
    ResponseIncompleteEvent,
    ResponseInProgressEvent,
    ResponseOutputItemAddedEvent,
    ResponseOutputItemDoneEvent,
    ResponseOutputMessage,
    ResponseOutputTextDeltaEvent,
    ResponseOutputTextDoneEvent,
    ResponseReasoningItem,
    ResponseReasoningSummaryTextDeltaEvent,
    ResponseReasoningSummaryTextDoneEvent,
    ResponseStreamEvent,
    TextConfig,
    Tool,
    Usage,
)
from codex_open_client._version import __version__

__all__ = [
    # Client
    "CodexClient",
    # Auth
    "PendingLogin",
    "finish_login",
    "get_token",
    "login",
    "refresh",
    "start_login",
    # API helpers
    "build_headers",
    "get_account_id",
    # Errors
    "APIConnectionError",
    "APIError",
    "APITimeoutError",
    "AuthError",
    "CodexError",
    "ContextWindowError",
    "InvalidRequestError",
    "QuotaExceededError",
    "RateLimitError",
    "ServerError",
    "StreamError",
    # Types — input
    "ContentPart",
    "FunctionCallOutput",
    "InputImage",
    "InputItem",
    "InputMessage",
    "InputText",
    # Types — output
    "OutputContent",
    "OutputItem",
    "OutputText",
    "ResponseFunctionToolCall",
    "ResponseOutputMessage",
    "ResponseReasoningItem",
    "ReasoningSummary",
    # Types — response
    "ParsedResponse",
    "Response",
    "ResponseError",
    "Usage",
    # Types — tools & config
    "FormatConfig",
    "FunctionTool",
    "Tool",
    "Reasoning",
    "ResponseFormatJsonObject",
    "ResponseFormatJsonSchema",
    "ResponseFormatText",
    "TextConfig",
    # Types — model
    "Model",
    # Types — stream events
    "ResponseCompletedEvent",
    "ResponseCreatedEvent",
    "ResponseFailedEvent",
    "ResponseFunctionCallArgumentsDeltaEvent",
    "ResponseFunctionCallArgumentsDoneEvent",
    "ResponseInProgressEvent",
    "ResponseIncompleteEvent",
    "ResponseOutputItemAddedEvent",
    "ResponseOutputItemDoneEvent",
    "ResponseOutputTextDeltaEvent",
    "ResponseOutputTextDoneEvent",
    "ResponseReasoningSummaryTextDeltaEvent",
    "ResponseReasoningSummaryTextDoneEvent",
    "ResponseStreamEvent",
    # Version
    "__version__",
]
